CREATE TABLE SEMISTUDENT (
    STUID NUMBER constraint stu_pk primary key,
    STUNAME VARCHAR(500)
);

CREATE TABLE STUSCORE (
    STUID NUMBER constraint score_fk references SEMISTUDENT(STUID),
    MAJOR VARCHAR(500),
    SUBJECT VARCHAR(500),
    PROFESSOR VARCHAR(500),
    SCORE VARCHAR(500)    
);

CREATE TABLE STUINFO (
    STUID NUMBER constraint info_fk references SEMISTUDENT(STUID),
    ADDRESS VARCHAR(500),
    EMAIL VARCHAR(500)
);

CREATE TABLE SEMILOGIN (
    STUID NUMBER constraint login_fk references SEMISTUDENT(STUID),
    STUPSS VARCHAR(500)
);

INSERT INTO SEMISTUDENT VALUES (123123, '홍길동');

INSERT INTO STUSCORE VALUES (123123, '수학', '대수학', '김판서', 'A+');
INSERT INTO STUSCORE VALUES (123123, '수학', '영어회화', '알렉스', 'D');

INSERT INTO STUINFO VALUES (123123, '서울시 서울구 서울동', '123@naver.com');

INSERT INTO SEMILOGIN VALUES (123123, 'asdfg');

select * from SEMISTUDENT;



